Details Popup windows for the mobile and desktop version of my portfolio
LokurasRlz/Portfolio pull request #16
Opened 2022-07-20 19:32 UTC by LokurasRlz

Implemented Popup windows to the details of my projects both in desktop version and mobile version.

2022-07-20 20:31 UTC, wuletawwonte requested changes
# Hi @LokurasRlz 👋🏿👋🏿👋🏿  

Good job so far!
There are some issues that you still need to work on to go to the next project! You have only a few more steps and you are done! 💪 💪 💪 

![giphy](https://user-images.githubusercontent.com/74506933/153382064-ed760a8c-4f4a-48d6-b1f0-1aa9e5135097.gif)

## TO HIGHLIGHT: 
- Your project is professional ✔️ 
- Correct Github Flow ✔️
- Your PR has a proper title and description ✔️
- Nice commit history ✔️

## Required Changes ♻️
_Please check the comments under the review as well._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-20 20:31 UTC, wuletawwonte commented on index.html
>                      industry's
- [ ] The projects(workspace) section should be created dynamically with the information from the projects array (all the HTML of this section should be created when the page loads). Please remove the existing code(Already created HTML code for projects list), and instead the content should be added via JavaScript.

2022-07-20 20:31 UTC, wuletawwonte commented on style.css
> +}
- [ ] I think there should be a gap between the top of the viewport and the popup container. Please position the popup in the center of the screen as shown in the Figma template.

<p align="center">&nbsp;
 
| Figma Design |   Your Website |
| ---------- | ----------- |
 | ![Template 2- Detail](https://user-images.githubusercontent.com/12524453/180075629-3080d61f-1c71-4ef7-9c0a-fa2c026a0530.png) | ![Template 2- Detail output](https://user-images.githubusercontent.com/12524453/180075676-ba9eebaf-62b7-481a-9168-56691473cd7d.png) |
</p>

2022-07-20 23:35 UTC, vickymarz requested changes
Hi @LokurasRlz , 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 23:35 UTC, vickymarz commented on style.css
> +.popupDesktop {
- [ ] As the previous reviewer has earlier suggested, kindly ensure that your popup is positioned in the center of the screen as shown in the Figma template for the desktop view 👍 . It is well positioned in the mobile view but on the desktop view, it is fixed to the top. Please fix it. 

Perhaps you can give the entire popup container width of 100% and then use flexbox(`justify-content: center` and `align-items: center`) to center the popup itself in the container 🤓 that way it will position perfectly at the center.

2022-07-21 00:05 UTC, vickymarz approved these changes
Hi @LokurasRlz , 

# 🟢  Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 00:08 UTC, merged